import { createScreenEffectDocument, screenEffectDocumentSchema, type MusicModuleConfig, type TimerDefinition } from "@stream-jams/core";
import { expect, test } from "@playwright/test";
import { readFile } from "node:fs/promises";
import { resolve } from "node:path";
import { createProviderSecurityRuntimeFixture } from "../../apps/server/src/test-support/provider-security-runtime-fixture.js";

test.use({ trace: "off", screenshot: "off", video: "off" });

test("rebuilt Effects and Timer editors preserve saved drafts, preview and event rules", async ({ page }, testInfo) => {
  const fixture = await createProviderSecurityRuntimeFixture();
  try {
    await fixture.start();
    expect((await fixture.request("/health")).status).toBe(200);
    const errors: string[] = [];
    page.on("pageerror", error => errors.push(error.message));
    page.on("console", entry => { if (entry.type() === "error") errors.push(entry.text()); });
    const imported = await fetch(`${fixture.runtime.url}/assets/import`, { method: "POST", headers: { ...fixture.headers, "content-type": "application/octet-stream", "x-stream-jams-file-name": "disposable-effect.png", "x-stream-jams-mime-type": "image/png" }, body: new Uint8Array(await readFile(resolve("apps/web/public/storybook-assets/tiny-image.png"))) });
    expect(imported.status).toBe(201);
    const asset = await imported.json() as { id: string };
    const base = createScreenEffectDocument({ id: "disposable-effect", name: "Disposable effect", defaultVariantId: "fixture-variant" });
    const effectDocument = screenEffectDocumentSchema.parse({ ...base, variants: [{ ...base.variants[0], visual: { mediaType: "image", assetId: asset.id, layout: { x: 0, y: 0, width: 1920, height: 1080, zIndex: 0 } }, visualOutputs: { browserSource: true, desktop: false } }] });
    expect((await fixture.request("/screen-effects", "POST", effectDocument)).status).toBe(201);
    await fixture.stop();
    await fixture.start();
    expect((await fixture.request("/health")).status).toBe(200);
    await page.setViewportSize({ width: 1500, height: 1100 });
    await page.goto(`${fixture.runtime.url}/manage/modules/screen-effects/editor/${effectDocument.id}`);
    await page.getByRole("textbox", { name: "Variant name" }).fill("Disposable " + "variant-name".repeat(10));
    await page.getByRole("spinbutton", { name: "Variant weight" }).fill("7");
    await page.getByRole("spinbutton", { name: "Visual width" }).fill("1200");
    await page.getByRole("button", { name: "Play preview" }).click();
    await expect(page.getByRole("button", { name: "Stop preview" })).toBeEnabled();
    await page.getByRole("checkbox", { name: "Mute preview" }).uncheck();
    await page.getByRole("button", { name: "Stop preview" }).click();
    await expect(page.getByRole("button", { name: "Stop preview" })).toBeDisabled();
    await page.screenshot({ path: testInfo.outputPath("effects-desktop-light-fields.png") });
    await page.getByRole("tab", { name: "Effect", exact: true }).click();
    await page.getByRole("textbox", { name: "Effect name" }).fill("Disposable " + "effect-name".repeat(10));
    await page.getByRole("button", { name: "Save", exact: true }).click();
    await expect(page.getByText("Screen Effect saved.", { exact: true })).toBeVisible();
    const savedEffect = screenEffectDocumentSchema.parse(await (await fixture.request(`/screen-effects/${effectDocument.id}`)).json());
    expect(savedEffect.variants[0]?.weight).toBe(7);
    expect(savedEffect.variants[0]?.visual?.layout.width).toBe(1200);
    await page.evaluate(() => localStorage.setItem("stream-jams-theme", "dark"));
    await page.reload();
    await page.evaluate(() => { document.documentElement.dir = "rtl"; });
    await page.setViewportSize({ width: 900, height: 1100 });
    await page.getByRole("spinbutton", { name: "Variant weight" }).scrollIntoViewIfNeeded();
    await page.screenshot({ path: testInfo.outputPath("effects-tablet-dark-rtl-fields.png") });
    await page.setViewportSize({ width: 390, height: 900 });
    await expect(page.getByRole("button", { name: "Back to Screen Effects" })).toBeVisible();
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await page.screenshot({ path: testInfo.outputPath("effects-390-dark-rtl.png") });

    await page.setViewportSize({ width: 1200, height: 1000 });
    await page.goto(`${fixture.runtime.url}/manage/modules/timers`);
    await page.getByRole("button", { name: "New timer" }).click();
    const timer = page.getByRole("dialog", { name: "Create timer", exact: true });
    await timer.getByRole("textbox", { name: "Name", exact: true }).fill("Disposable " + "timer-name".repeat(9));
    await timer.getByRole("spinbutton", { name: "Duration (seconds)" }).fill("75");
    await timer.getByRole("button", { name: "Add event rule" }).click();
    const rule = timer.getByRole("group", { name: "Rule 1" });
    await rule.getByRole("combobox", { name: "Event type" }).selectOption("cheer");
    await rule.getByRole("combobox", { name: "Action", exact: true }).selectOption("increment");
    await rule.getByRole("spinbutton", { name: "Adjustment (seconds)" }).fill("15");
    const quantity = rule.getByRole("spinbutton", { name: "Quantity per adjustment (blank for fixed time)" });
    await quantity.fill("10");
    await quantity.fill("");
    await timer.getByRole("checkbox", { name: "Browser Source", exact: true }).uncheck();
    await page.setViewportSize({ width: 390, height: 1000 });
    await quantity.scrollIntoViewIfNeeded();
    await page.screenshot({ path: testInfo.outputPath("timer-390-dark-rules.png") });
    await timer.getByRole("button", { name: "Create timer", exact: true }).click();
    await expect(timer).toHaveCount(0);
    const timers = await (await fixture.request("/timers")).json() as TimerDefinition[];
    expect(timers[0]).toMatchObject({ durationMs: 75000, outputs: { browserSource: false }, eventRules: [{ action: "increment", amountMs: 15000, quantityUnit: null }] });
    await page.getByRole("combobox", { name: "Orientation" }).selectOption("horizontal");
    await page.getByRole("spinbutton", { name: "Maximum shown" }).fill("4");
    await page.getByRole("button", { name: "Save overlay layout" }).click();
    await expect(page.getByText("Timer overlay layout saved.", { exact: true })).toBeVisible();
    await page.getByRole("radiogroup", { name: "Timer profile" }).getByText("Vertical", { exact: true }).click();
    await expect(page.getByRole("radio", { name: "Vertical", exact: true })).toBeChecked();
    await page.getByRole("spinbutton", { name: "Maximum shown" }).scrollIntoViewIfNeeded();
    await page.screenshot({ path: testInfo.outputPath("timer-390-dark-stack.png") });

    expect(errors).toEqual([]);
  } finally { await fixture.close(); }
});

test("rebuilt Music editor preserves numeric, typography, CSS and desktop controls", async ({ page }, testInfo) => {
  const fixture = await createProviderSecurityRuntimeFixture();
  try {
    await fixture.start();
    expect((await fixture.request("/health")).status).toBe(200);
    const errors: string[] = [];
    page.on("pageerror", error => errors.push(error.message));
    page.on("console", entry => { if (entry.type() === "error") errors.push(entry.text()); });
    await page.setViewportSize({ width: 390, height: 1000 });
    await page.goto(`${fixture.runtime.url}/manage/modules/music`);
    await page.evaluate(() => localStorage.setItem("stream-jams-theme", "dark"));
    await page.reload();
    await page.goto(`${fixture.runtime.url}/manage/modules/music`);
    await page.getByRole("button", { name: "Expand appearance" }).click();
    const width = page.getByRole("spinbutton", { name: "Widget width (px)", exact: true });
    await width.fill("");
    await width.blur();
    await expect(width).toHaveAttribute("aria-invalid", "true");
    const numberError = page.getByRole("alert");
    await expect(numberError).toContainText("whole number");
    await expect(width).toHaveAttribute("aria-describedby", await numberError.getAttribute("id") ?? "");
    await expect(width).toHaveCSS("border-color", await numberError.evaluate(node => getComputedStyle(node).color));
    await page.locator(".mantine-TextInput-root").filter({ has: width }).scrollIntoViewIfNeeded();
    await numberError.scrollIntoViewIfNeeded();
    await expect(page.getByText("Widget width (px)", { exact: true })).toBeInViewport();
    await expect(numberError).toBeInViewport();
    await page.screenshot({ path: testInfo.outputPath("music-390-dark-invalid-width.png") });
    await width.fill("700");
    await width.press("Enter");
    await page.getByRole("combobox", { name: "Appearance component" }).selectOption("title");
    await page.getByRole("combobox", { name: "Title preset", exact: true }).selectOption("monospace");
    await page.getByText("More text options", { exact: true }).click();
    await page.getByRole("combobox", { name: "Title weight", exact: true }).selectOption("600");
    await page.getByRole("checkbox", { name: "Italic title" }).check();
    await page.getByRole("spinbutton", { name: "Title letter spacing (px)" }).fill("-1.5");
    await page.getByRole("spinbutton", { name: "Title letter spacing (px)" }).blur();
    await page.screenshot({ path: testInfo.outputPath("music-390-dark-typography.png") });
    await page.getByRole("button", { name: "Expand custom CSS" }).click();
    const css = page.getByRole("textbox", { name: "Custom CSS" });
    await css.fill(".unsupported { color: red; }");
    await expect(css).toHaveAttribute("aria-invalid", "true");
    await expect(css).toHaveAttribute("aria-describedby", "music-css-help music-css-error");
    await css.scrollIntoViewIfNeeded();
    await page.screenshot({ path: testInfo.outputPath("music-390-dark-invalid-css.png") });
    await page.getByRole("button", { name: "Clear CSS" }).click();
    await page.getByRole("button", { name: "Save Music appearance" }).click();
    await expect(page.getByText("All changes saved", { exact: true })).toBeVisible();
    const music = await (await fixture.request("/overlay-modules/music/config")).json() as { config: MusicModuleConfig };
    expect(music.config.profiles.landscape.views.full.widthPx).toBe(700);
    await page.setViewportSize({ width: 900, height: 1100 });
    await page.evaluate(() => { document.documentElement.dir = "rtl"; });
    await page.getByRole("button", { name: "Expand desktop overlay placement" }).click();
    await page.getByRole("spinbutton", { name: "Desktop Music scale (%)" }).scrollIntoViewIfNeeded();
    await page.screenshot({ path: testInfo.outputPath("music-tablet-dark-rtl-desktop.png") });
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
    await fixture.stop();
    await fixture.start();
    expect((await fixture.request("/health")).status).toBe(200);
    await page.reload();
    await page.getByRole("button", { name: "Expand appearance" }).click();
    await expect(page.getByRole("spinbutton", { name: "Widget width (px)", exact: true })).toHaveValue("700");
    expect(errors).toEqual([]);
  } finally { await fixture.close(); }
});
