import { expect, test } from "@playwright/test";
import type { MusicModuleConfig } from "../../packages/core/dist/index.js";
import { startMusicTestRuntime } from "./music-test-runtime.js";

test("Music editor saves dragged and resized components to the live output", async ({ page, context }) => {
  test.setTimeout(90_000);
  const fixture = await startMusicTestRuntime();
  try {
    fixture.pear.setSong({ status: 200, body: { videoId: "editor-song", title: "Layout Track", artist: "Fixture", songDuration: 180, elapsedSeconds: 12, isPaused: false } });
    await fixture.register();
    const saved = await fixture.request<{ config: MusicModuleConfig }>("/overlay-modules/music/config");
    await fixture.request("/overlay-modules/music/config", "PUT", { enabled: true, config: saved.config });
    const output = await fixture.request<{ url: string }>("/management/overlay-outputs/keys", "POST", { overlayId: "default", scope: "module", moduleId: "music", purpose: "live", targetProfileId: "landscape" });
    await page.goto(`${fixture.url}/manage/modules/music`);
    const preview = page.getByRole("region", { name: "Music preview" });
    await expect(preview.getByTestId("music-widget")).toBeVisible();
    await expect(page.getByRole("button", { name: "Expand configuration" })).toHaveAttribute("aria-expanded", "false");
    await page.getByRole("button", { name: "Expand configuration" }).click();
    const color = page.getByLabel("Title color", { exact: true });
    await color.fill("#123456");
    await expect(page.getByLabel("Title RGBA", { exact: true })).toHaveValue("#123456FF");
    await page.getByRole("button", { name: "Collapse configuration" }).click();
    await page.getByRole("button", { name: "Edit component layout" }).click();
    const width = page.getByLabel("Title width (px)");
    await width.fill("200"); await width.press("Tab");
    const move = page.getByRole("button", { name: "Move Title", exact: true });
    const originalX = Number(await page.getByLabel("Title X (px)").inputValue());
    const box = (await move.boundingBox())!;
    await page.mouse.move(box.x + 10, box.y + 10);
    await page.mouse.down(); await page.mouse.move(box.x - 10, box.y + 15, { steps: 5 }); await page.mouse.up();
    await expect.poll(async () => Number(await page.getByLabel("Title X (px)").inputValue())).toBeLessThan(originalX);
    const resize = page.getByRole("button", { name: "Resize Title", exact: true });
    const corner = (await resize.boundingBox())!;
    await page.mouse.move(corner.x + corner.width / 2, corner.y + corner.height / 2);
    await page.mouse.down(); await page.mouse.move(corner.x + corner.width / 2 + 20, corner.y + corner.height / 2 + 8, { steps: 5 }); await page.mouse.up();
    await expect.poll(async () => Number(await width.inputValue())).toBeGreaterThan(200);
    await move.focus(); await move.press("ArrowRight");
    expect((await fixture.request<{ config: MusicModuleConfig }>("/overlay-modules/music/config")).config.profiles.landscape.views.full.componentLayout).toBeNull();
    await page.getByRole("button", { name: "Save Music appearance" }).click();
    await expect(page.getByText("All changes saved")).toBeVisible();
    const config = (await fixture.request<{ config: MusicModuleConfig }>("/overlay-modules/music/config")).config;
    const title = config.profiles.landscape.views.full.componentLayout!.title;
    const live = await context.newPage();
    await live.goto(output.url);
    await expect(live.getByTestId("music-widget").locator(".sj-title")).toHaveCSS("left", `${title.x}px`);
    await expect(live.getByTestId("music-widget").locator(".sj-title")).toHaveCSS("width", `${title.width}px`);
    await expect(live.getByRole("button", { name: "Move Title" })).toHaveCount(0);
    await page.reload();
    await page.getByRole("button", { name: "Edit component layout" }).click();
    await expect(page.getByLabel("Title X (px)")).toHaveValue(String(title.x));
    await expect(page.getByLabel("Title width (px)")).toHaveValue(String(title.width));
    await page.getByRole("button", { name: "Done editing" }).click();
    await page.getByRole("button", { name: "Expand custom css" }).click();
    await page.getByLabel("Custom CSS", { exact: true }).fill(".sj-title { color: red; }");
    await page.getByLabel("Enable custom CSS").check();
    await expect(page.getByRole("button", { name: "Edit component layout" })).toBeDisabled();
    await page.getByRole("button", { name: "Collapse custom css" }).click();
    await page.getByRole("button", { name: "Disable custom CSS" }).click();
    await expect(page.getByRole("button", { name: "Edit component layout" })).toBeEnabled();
    await page.getByRole("button", { name: "Reset automatic layout" }).click();
    await page.getByRole("button", { name: "Save Music appearance" }).click();
    await expect(page.getByText("All changes saved")).toBeVisible();
    const reset = (await fixture.request<{ config: MusicModuleConfig }>("/overlay-modules/music/config")).config;
    expect(reset.profiles.landscape.views.full.componentLayout).toBeNull();
    expect(reset.css.source).toBe(".sj-title { color: red; }");
    expect(reset.css.enabled).toBe(false);
  } finally { await fixture.close(); }
});
