import { mkdtemp, rm } from "node:fs/promises";
import { createServer } from "node:net";
import { tmpdir } from "node:os";
import { join, resolve } from "node:path";
import { expect, test } from "@playwright/test";
import { InMemorySecretStore } from "../../packages/test-support/dist/index.js";
import { createDefaultAppConfig } from "../../apps/server/dist/config/default-config.js";
import { FileConfigStore } from "../../apps/server/dist/config/file-config-store.js";
import { startLocalRuntime, type StartedLocalRuntime } from "../../apps/server/dist/runtime/start-local-runtime.js";

test("retains a subathon paused and applies saved event rules and live manual corrections", async ({ page }, testInfo) => {
  test.setTimeout(90_000);
  const root = await mkdtemp(join(tmpdir(), "stream-jams-persistent-timers-"));
  const listener = createServer();
  await new Promise<void>(done => listener.listen(0, "127.0.0.1", done));
  const address = listener.address();
  if (address === null || typeof address === "string") throw new Error("Expected isolated port");
  const port = address.port;
  await new Promise<void>((done, reject) => listener.close(error => error ? reject(error) : done()));
  const config = { ...createDefaultAppConfig(root), server: { host: "127.0.0.1" as const, port } };
  const options = { homeDirectory: root, webBuildDirectory: resolve("apps/web/dist"), configStore: new FileConfigStore({ configFilePath: join(root, "config.json"), defaultConfig: config }), environment: {}, secretStore: new InMemorySecretStore() };
  let runtime: StartedLocalRuntime | undefined;
  try {
    runtime = await startLocalRuntime(options);
    await page.goto(`${runtime.url}/manage/modules/timers`);
    await page.getByRole("button", { name: "Enable Timers module" }).click();
    await page.getByRole("dialog", { name: "Enable Timers module?" }).getByRole("button", { name: "Confirm change" }).click();
    await expect(page.getByRole("button", { name: "Disable Timers module" })).toBeVisible();
    await page.getByRole("button", { name: "New timer" }).click();
    const dialog = page.getByRole("dialog", { name: "Create timer" });
    await dialog.getByLabel("Name", { exact: true }).fill("Subathon");
    await dialog.getByLabel("Duration (seconds)").fill("600");
    await dialog.getByRole("button", { name: "Add event rule" }).click();
    await dialog.getByLabel("Event type").selectOption("cheer");
    await dialog.getByRole("combobox", { name: "Action", exact: true }).selectOption("increment");
    await dialog.getByLabel("Adjustment (seconds)").fill("30");
    await dialog.getByLabel("Quantity per adjustment (blank for fixed time)").fill("100");
    await dialog.getByRole("button", { name: "Create timer", exact: true }).click();
    await expect(dialog).not.toBeVisible();
    const definition = runtime.composition.timerManagementService.listDefinitions().find(item => item.label === "Subathon")!;
    expect(definition.eventRules?.[0]).toMatchObject({ eventType: "cheer", inactiveBehavior: "ignore", quantityUnit: 100 });
    const cheer = { id: "cheer-acceptance", providerId: "twitch", sourcePlatform: "twitch", ingestProvider: "twitch", occurredAt: new Date().toISOString(), actor: { id: "viewer", displayName: "Viewer" }, message: null, metadata: {}, type: "cheer", amount: 200 };
    await runtime.composition.eventIngestionService.ingestNormalizedEvent({ ...cheer, id: "idle-cheer" });
    expect(runtime.composition.timerRuntimeCoordinator.getState(definition.id)).toBeNull();
    await runtime.composition.timerRuntimeCoordinator.start(definition.id);
    await runtime.composition.timerRuntimeCoordinator.pause(definition.id);
    const before = runtime.composition.timerRuntimeCoordinator.getState(definition.id);
    if (before?.status !== "paused") throw new Error("Expected paused subathon");
    expect((await runtime.composition.eventIngestionService.ingestNormalizedEvent(cheer)).status).toBe("accepted");
    expect((await runtime.composition.eventIngestionService.ingestNormalizedEvent(cheer)).status).toBe("duplicate");
    expect(runtime.composition.timerRuntimeCoordinator.getState(definition.id)).toMatchObject({ status: "paused", remainingMs: before.remainingMs + 60_000 });
    await page.getByRole("article", { name: "Subathon timer" }).getByRole("button", { name: "Edit" }).click();
    const edit = page.getByRole("dialog", { name: "Edit Subathon" });
    await edit.getByRole("combobox", { name: "Adjustment", exact: true }).selectOption("set");
    await edit.getByLabel("Time (seconds)").fill("300");
    await edit.getByRole("button", { name: "Apply adjustment" }).click();
    await expect.poll(() => runtime!.composition.timerRuntimeCoordinator.getState(definition.id)).toMatchObject({ status: "paused", remainingMs: 300_000 });
    await runtime.composition.timerRuntimeCoordinator.adjust(definition.id, { action: "set", amountMs: 300000 });
    const sessionResponse = await page.request.post(`${runtime.url}/auth/management/sessions`);
    expect(sessionResponse.ok()).toBe(true);
    const session = await sessionResponse.json() as { id: string; csrfToken: string };
    const outputResponse = await page.request.post(`${runtime.url}/management/overlay-outputs/keys`, { headers: { authorization: `Bearer ${session.id}`, "x-stream-jams-csrf": session.csrfToken }, data: { overlayId: "default", moduleId: "timers", purpose: "live", scope: "module", targetProfileId: "landscape" } });
    expect(outputResponse.ok()).toBe(true);
    const output = await outputResponse.json() as { url: string };
    const overlay = await page.context().newPage();
    await overlay.goto(output.url);
    const overlayValue = overlay.getByTestId(`timer-value-${definition.id}`);
    await expect(overlayValue).toHaveText("5:00");
    const applyCorrection = async (action: string, seconds: string) => {
      await edit.getByRole("combobox", { name: "Adjustment", exact: true }).selectOption(action);
      await edit.getByLabel("Time (seconds)").fill(seconds);
      await edit.getByRole("button", { name: "Apply adjustment" }).click();
    };
    await applyCorrection("increment", "60");
    await expect(overlayValue).toHaveText("6:00");
    await applyCorrection("decrement", "30");
    await expect(overlayValue).toHaveText("5:30");
    await applyCorrection("set", "300");
    await expect(overlayValue).toHaveText("5:00");
    await page.screenshot({ path: testInfo.outputPath("timer-editor.png") });
    await runtime.composition.timerRuntimeCoordinator.resume(definition.id);
    await runtime.close();
    runtime = await startLocalRuntime(options);
    const recovered = runtime.composition.timerRuntimeCoordinator.getState(definition.id);
    expect(recovered?.status).toBe("paused");
    if (recovered?.status !== "paused") throw new Error("Expected paused recovery");
    expect(recovered.remainingMs).toBeGreaterThan(290_000);
    await page.goto(`${runtime.url}/operator`);
    const card = page.getByRole("article").filter({ has: page.getByText("Subathon", { exact: true }) });
    await expect(card.getByRole("button", { name: "Resume", exact: true })).toBeVisible();
    await card.getByRole("combobox", { name: "Adjustment", exact: true }).selectOption("decrement");
    await card.getByLabel("Time (seconds)").fill("30");
    await card.getByRole("button", { name: "Apply adjustment" }).click();
    await expect.poll(() => runtime!.composition.timerRuntimeCoordinator.getState(definition.id)).toMatchObject({ status: "paused", remainingMs: recovered.remainingMs - 30_000 });
    await page.screenshot({ path: testInfo.outputPath("operator-timer.png") });
    await overlay.reload();
    await expect(overlayValue).toHaveText("4:30");
    await card.getByLabel("Time (seconds)").fill("600");
    await card.getByRole("button", { name: "Apply adjustment" }).click();
    await expect(overlayValue).toHaveText("0:00");
    await expect(overlayValue).toHaveCount(0);
    await overlay.close();
    await page.goto(`${runtime.url}/manage/modules/timers`);
    await page.getByRole("button", { name: "New timer" }).click();
    const catDialog = page.getByRole("dialog", { name: "Create timer" });
    await catDialog.getByLabel("Name", { exact: true }).fill("Cat paws");
    await catDialog.getByLabel("Duration (seconds)").fill("60");
    await catDialog.getByRole("button", { name: "Add event rule" }).click();
    await catDialog.getByLabel("Event type").selectOption("channel_point_redemption");
    await catDialog.getByLabel("Reward ID (optional)").fill("cat-paws");
    await catDialog.getByRole("combobox", { name: "Action", exact: true }).selectOption("start");
    await catDialog.getByRole("button", { name: "Create timer", exact: true }).click();
    await expect(catDialog).not.toBeVisible();
    const cat = runtime.composition.timerManagementService.listDefinitions().find(item => item.label === "Cat paws")!;
    const redemption = { ...cheer, type: "channel_point_redemption", amount: null, rewardId: "other", rewardTitle: "Reward", userInput: null };
    await runtime.composition.eventIngestionService.ingestNormalizedEvent({ ...redemption, id: "other-reward" });
    expect(runtime.composition.timerRuntimeCoordinator.getState(cat.id)).toBeNull();
    await runtime.composition.eventIngestionService.ingestNormalizedEvent({ ...redemption, rewardId: "cat-paws", id: "cat-reward" });
    const catRun = runtime.composition.timerRuntimeCoordinator.getState(cat.id);
    expect(catRun?.status).toBe("running");
    await runtime.composition.eventIngestionService.ingestNormalizedEvent({ ...redemption, rewardId: "cat-paws", id: "cat-reward-again" });
    expect(runtime.composition.timerRuntimeCoordinator.getState(cat.id)).toEqual(catRun);
    await runtime.composition.timerRuntimeCoordinator.stop(cat.id);
    await runtime.close(); runtime = await startLocalRuntime(options);
    expect(runtime.composition.timerRuntimeCoordinator.listStates()).toEqual([]);
  } finally {
    await runtime?.close();
    await rm(root, { recursive: true, force: true });
  }
});
